export const modes = {
    STATIC: 'static',
    SIMPLE_SELECT: 'simple_select',
    DIRECT_SELECT: 'direct_select',
    DRAW_LINE_STRING: 'draw_line_string',
    DRAW_POLYGON: 'draw_polygon',
    DRAW_POINT: 'draw_point',
    DRAW_CIRCLE: 'draw_circle',
    DRAW_RECTANGLE: 'draw_rectangle',
    DRAW_MARKER: 'draw_marker',
    DRAW_ATTACK_ARROW: 'draw_attack_arrow',
    DRAW_ARC: 'draw_arc',
    DRAW_TAILED_ATTACK_ARROW: 'draw_tailed_attack_arrow',
    DRAQ_STRAIGHT_ARROW: 'draw_straight_arrow',
    DRAW_ELLIPSE: 'draw_ellipse',
    DRAW_TEXT: 'draw_text',
    DRAW_CURVE: 'draw_curve',
    DRAW_SECTOR: 'draw_sector',
    DRAW_FREEHAND_LINE: 'draw_freehand_line',
    DRAW_FREEHAND_POLYGON: 'draw_freehand_polygon',
};

export const geojsonTypes = {
    FEATURE: 'Feature',
    POLYGON: 'Polygon',
    LINE_STRING: 'LineString',
    POINT: 'Point',
    FEATURE_COLLECTION: 'FeatureCollection',
    MULTI_PREFIX: 'Multi',
    MULTI_POINT: 'MultiPoint',
    MULTI_LINE_STRING: 'MultiLineString',
    MULTI_POLYGON: 'MultiPolygon',
    CIRCLE: 'Polygon',
    RECTANGLE: 'Polygon',
    MARKER: 'Marker',
    ATTACK_ARROW: 'Polygon',
    ARC: 'LineString',
    TAILED_ATTACK_ARROW: 'Polygon',
    STRAIGHT_ARROW: 'LineString',
    ELLIPSE: 'Polygon',
    TEXT: 'Text',
    CURVE: 'LineString',
    SECTOR: 'Polygon',
    FREEHAND_LINE: 'LineString',
    FREEHAND_POLYGON: 'Polygon',
};
